version: '3'

services:
  mockidp:
    image: bjornskoglund/mock-idp:0.4.0
    ports:
      - "5001:5000"
    volumes:
      - ./mockidp.yaml:/usr/local/mock-idp/mockidp.yaml
    restart: always

  metadata-server:
    image: nginx:alpine
    ports:
      - "5002:80"
    volumes:
      - ./idp-metadata/metadata.xml:/usr/share/nginx/html/metadata.xml
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway" 